### ISSUE TITLE
AdvancedUserInterface is deprecated

### ISSUE THREAD

**Issue by cybernet** [dant89/symfony-4-basic-user-system#3]
"In Symfony 4.1 we have deprecated the **AdvancedUserInterface**"

[AdvancedUserInterface is deprecated](https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-advanceduserinterface)

**Comment by dant89** [comment]
Thanks, will tweak this in the next release

**Comment by dant89** [comment]
Fixed in this commit: https://github.com/dant89/symfony-4-basic-user-system/commit/6f5a1a94ca8314814006770fcd19fed046445488
